In [1]:
from model_loader.model_loader import CasesModel, DeathModel

In [2]:
cm = CasesModel(model_location="model_data/models/rf_cases_trainsplit.pkl", model_json="model_data/json/cases_model.json", country_lookup="model_data/country_data_full.csv")

In [3]:
dm = DeathModel(model_location="model_data/models/death_model.pkl", model_json="model_data/json/deathmodel_cols.json", country_lookup="model_data/death_model_full.csv")

In [5]:
import pandas as pd

df = pd.read_parquet("model_data/country_data_full.parquet")
df.to_csv("model_data/country_data_full.csv")

df = pd.read_parquet("model_data/death_model_full.parquet")
df.to_csv("model_data/death_model_full.csv")

In [4]:
date_str = "2020-04-30"
country = "China"

In [5]:
flag = cm.get_flag(date= date_str, country=country)

In [6]:
df

        dateRep  deaths                     countriesAndTerritories  flag
72   2019-12-31       0                                 Afghanistan   0.0
164  2019-12-31       0                                     Algeria   0.0
267  2019-12-31       0                                     Armenia   0.0
350  2019-12-31       0                                   Australia   0.0
433  2019-12-31       0                                     Austria   0.0
509  2019-12-31       0                                  Azerbaijan   0.0
596  2019-12-31       0                                     Bahrain   0.0
684  2019-12-31       0                                     Belarus   0.0
767  2019-12-31       0                                     Belgium   0.0
885  2019-12-31       0                                      Brazil   0.0
994  2019-12-31       0                                    Cambodia   0.0
1087 2019-12-31       0                                      Canada   0.0
1153 2019-12-31       0  Cases_on_an_international_conveyance_Japan   0.0
1267 2019-12-31       0                                       China   0.0
1390 2019-12-31       0                                     Croatia   0.0
1492 2019-12-31       0                              Czech_Republic   0.0
1585 2019-12-31       0                                     Denmark   0.0
1663 2019-12-31       0                          Dominican_Republic   0.0
1741 2019-12-31       0                                     Ecuador   0.0
1820 2019-12-31       0                                       Egypt   0.0
1911 2019-12-31       0                                     Estonia   0.0
2012 2019-12-31       0                                     Finland   0.0
2095 2019-12-31       0                                      France   0.0
2193 2019-12-31       0                                     Georgia   0.0
2276 2019-12-31       0                                     Germany   0.0
2369 2019-12-31       0                                      Greece   0.0
2523 2019-12-31       0                                     Iceland   0.0
2605 2019-12-31       0                                       India   0.0
2681 2019-12-31       0                                   Indonesia   0.0
2764 2019-12-31       0                                        Iran   0.0
...         ...     ...                                         ...   ...
5150 2020-03-22       0                                    Slovakia   0.0
5165 2020-03-22       1                                    Slovenia   0.0
5182 2020-03-22       0                                     Somalia   0.0
5188 2020-03-22       0                                South_Africa   0.0
5203 2020-03-22     104                                 South_Korea   2.0
5286 2020-03-22    1326                                       Spain   9.0
5369 2020-03-22       0                                   Sri_Lanka   0.0
5443 2020-03-22       1                                       Sudan   0.0
5452 2020-03-22       0                                    Suriname   0.0
5455 2020-03-22      20                                      Sweden   0.0
5538 2020-03-22      56                                 Switzerland   0.0
5621 2020-03-22       2                                      Taiwan   0.0
5702 2020-03-22       1                                    Thailand   0.0
5778 2020-03-22       0                                 Timor_Leste   0.0
5779 2020-03-22       0                                        Togo   0.0
5788 2020-03-22       0                         Trinidad_and_Tobago   0.0
5798 2020-03-22       1                                     Tunisia   0.0
5812 2020-03-22      21                                      Turkey   0.0
5821 2020-03-22       0                                      Uganda   0.0
5822 2020-03-22       3                                     Ukraine   0.0
5831 2020-03-22       2                        United_Arab_Emirates   0.0
5908 2020-03-22     233                              United_Kingdom   4.0
5991 2020-03-22       0                 United_Republic_of_Tanzania   0.0
5997 2020-03-22     340                    United_States_of_America   5.0
6080 2020-03-22       0                                     Uruguay   0.0
6088 2020-03-22       0                                  Uzbekistan   0.0
6095 2020-03-22       0                                   Venezuela   0.0
6103 2020-03-22       0                                     Vietnam   0.0
6182 2020-03-22       0                                      Zambia   0.0
6186 2020-03-22       0                                    Zimbabwe   0.0

[6188 rows x 4 columns]

In [6]:
cm.country_df[cm.country_df.countriesAndTerritories == country].tail()

        dateRep    cases countriesAndTerritories  flag
1522 2020-03-27  3821198                   China  69.0
1521 2020-03-28  3903144                   China  70.0
1520 2020-03-29  3985203                   China  71.0
1519 2020-03-30  4067360                   China  72.0
1518 2020-03-31  4149601                   China  73.0

In [7]:
dm.country_df[dm.country_df.countriesAndTerritories == country].tail()

        dateRep  deaths countriesAndTerritories  flag
1189 2020-03-18    3242                   China  51.0
1188 2020-03-19    3250                   China  52.0
1187 2020-03-20    3254                   China  53.0
1186 2020-03-21    3261                   China  54.0
1185 2020-03-22    3267                   China  55.0

In [8]:
flag

{'flag': 103.0}

In [9]:
cm.gen_prediction(date=date_str, country=country)

flag value 103.0

[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 100 out of 100 | elapsed:    0.0s finished

82150

In [12]:
cm.feature_array[0] =103

In [13]:
cm.feature_array[40] = 1

In [12]:
dm.gen_prediction(date=date_str, country=country)

3262

In [16]:
cm.model_headers

['flag',
 'countriesAndTerritories_Afghanistan',
 'countriesAndTerritories_Albania',
 'countriesAndTerritories_Algeria',
 'countriesAndTerritories_Andorra',
 'countriesAndTerritories_Angola',
 'countriesAndTerritories_Anguilla',
 'countriesAndTerritories_Antigua_and_Barbuda',
 'countriesAndTerritories_Argentina',
 'countriesAndTerritories_Armenia',
 'countriesAndTerritories_Aruba',
 'countriesAndTerritories_Australia',
 'countriesAndTerritories_Austria',
 'countriesAndTerritories_Azerbaijan',
 'countriesAndTerritories_Bahamas',
 'countriesAndTerritories_Bahrain',
 'countriesAndTerritories_Bangladesh',
 'countriesAndTerritories_Barbados',
 'countriesAndTerritories_Belarus',
 'countriesAndTerritories_Belgium',
 'countriesAndTerritories_Belize',
 'countriesAndTerritories_Benin',
 'countriesAndTerritories_Bermuda',
 'countriesAndTerritories_Bhutan',
 'countriesAndTerritories_Bolivia',
 'countriesAndTerritories_Bosnia_and_Herzegovina',
 'countriesAndTerritories_Brazil',
 'countriesAndTerritories_British_Virgin_Islands',
 'countriesAndTerritories_Brunei_Darussalam',
 'countriesAndTerritories_Bulgaria',
 'countriesAndTerritories_Burkina_Faso',
 'countriesAndTerritories_Cambodia',
 'countriesAndTerritories_Cameroon',
 'countriesAndTerritories_Canada',
 'countriesAndTerritories_Cape_Verde',
 'countriesAndTerritories_Cases_on_an_international_conveyance_Japan',
 'countriesAndTerritories_Cayman_Islands',
 'countriesAndTerritories_Central_African_Republic',
 'countriesAndTerritories_Chad',
 'countriesAndTerritories_Chile',
 'countriesAndTerritories_China',
 'countriesAndTerritories_Colombia',
 'countriesAndTerritories_Congo',
 'countriesAndTerritories_Costa_Rica',
 'countriesAndTerritories_Cote_dIvoire',
 'countriesAndTerritories_Croatia',
 'countriesAndTerritories_Cuba',
 'countriesAndTerritories_Curacao',
 'countriesAndTerritories_Cyprus',
 'countriesAndTerritories_Czech_Republic',
 'countriesAndTerritories_Democratic_Republic_of_the_Congo',
 'countriesAndTerritories_Denmark',
 'countriesAndTerritories_Djibouti',
 'countriesAndTerritories_Dominica',
 'countriesAndTerritories_Dominican_Republic',
 'countriesAndTerritories_Ecuador',
 'countriesAndTerritories_Egypt',
 'countriesAndTerritories_El_Salvador',
 'countriesAndTerritories_Equatorial_Guinea',
 'countriesAndTerritories_Eritrea',
 'countriesAndTerritories_Estonia',
 'countriesAndTerritories_Eswatini',
 'countriesAndTerritories_Ethiopia',
 'countriesAndTerritories_Falkland_Islands_(Malvinas)',
 'countriesAndTerritories_Faroe_Islands',
 'countriesAndTerritories_Fiji',
 'countriesAndTerritories_Finland',
 'countriesAndTerritories_France',
 'countriesAndTerritories_French_Polynesia',
 'countriesAndTerritories_Gabon',
 'countriesAndTerritories_Gambia',
 'countriesAndTerritories_Georgia',
 'countriesAndTerritories_Germany',
 'countriesAndTerritories_Ghana',
 'countriesAndTerritories_Gibraltar',
 'countriesAndTerritories_Greece',
 'countriesAndTerritories_Greenland',
 'countriesAndTerritories_Grenada',
 'countriesAndTerritories_Guam',
 'countriesAndTerritories_Guatemala',
 'countriesAndTerritories_Guernsey',
 'countriesAndTerritories_Guinea',
 'countriesAndTerritories_Guinea_Bissau',
 'countriesAndTerritories_Guyana',
 'countriesAndTerritories_Haiti',
 'countriesAndTerritories_Holy_See',
 'countriesAndTerritories_Honduras',
 'countriesAndTerritories_Hungary',
 'countriesAndTerritories_Iceland',
 'countriesAndTerritories_India',
 'countriesAndTerritories_Indonesia',
 'countriesAndTerritories_Iran',
 'countriesAndTerritories_Iraq',
 'countriesAndTerritories_Ireland',
 'countriesAndTerritories_Isle_of_Man',
 'countriesAndTerritories_Israel',
 'countriesAndTerritories_Italy',
 'countriesAndTerritories_Jamaica',
 'countriesAndTerritories_Japan',
 'countriesAndTerritories_Jersey',
 'countriesAndTerritories_Jordan',
 'countriesAndTerritories_Kazakhstan',
 'countriesAndTerritories_Kenya',
 'countriesAndTerritories_Kosovo',
 'countriesAndTerritories_Kuwait',
 'countriesAndTerritories_Kyrgyzstan',
 'countriesAndTerritories_Laos',
 'countriesAndTerritories_Latvia',
 'countriesAndTerritories_Lebanon',
 'countriesAndTerritories_Liberia',
 'countriesAndTerritories_Libya',
 'countriesAndTerritories_Liechtenstein',
 'countriesAndTerritories_Lithuania',
 'countriesAndTerritories_Luxembourg',
 'countriesAndTerritories_Madagascar',
 'countriesAndTerritories_Malaysia',
 'countriesAndTerritories_Maldives',
 'countriesAndTerritories_Mali',
 'countriesAndTerritories_Malta',
 'countriesAndTerritories_Mauritania',
 'countriesAndTerritories_Mauritius',
 'countriesAndTerritories_Mexico',
 'countriesAndTerritories_Moldova',
 'countriesAndTerritories_Monaco',
 'countriesAndTerritories_Mongolia',
 'countriesAndTerritories_Montenegro',
 'countriesAndTerritories_Montserrat',
 'countriesAndTerritories_Morocco',
 'countriesAndTerritories_Mozambique',
 'countriesAndTerritories_Myanmar',
 'countriesAndTerritories_Namibia',
 'countriesAndTerritories_Nepal',
 'countriesAndTerritories_Netherlands',
 'countriesAndTerritories_New_Caledonia',
 'countriesAndTerritories_New_Zealand',
 'countriesAndTerritories_Nicaragua',
 'countriesAndTerritories_Niger',
 'countriesAndTerritories_Nigeria',
 'countriesAndTerritories_North_Macedonia',
 'countriesAndTerritories_Northern_Mariana_Islands',
 'countriesAndTerritories_Norway',
 'countriesAndTerritories_Oman',
 'countriesAndTerritories_Pakistan',
 'countriesAndTerritories_Palestine',
 'countriesAndTerritories_Panama',
 'countriesAndTerritories_Papua_New_Guinea',
 'countriesAndTerritories_Paraguay',
 'countriesAndTerritories_Peru',
 'countriesAndTerritories_Philippines',
 'countriesAndTerritories_Poland',
 'countriesAndTerritories_Portugal',
 'countriesAndTerritories_Puerto_Rico',
 'countriesAndTerritories_Qatar',
 'countriesAndTerritories_Romania',
 'countriesAndTerritories_Russia',
 'countriesAndTerritories_Rwanda',
 'countriesAndTerritories_Saint_Kitts_and_Nevis',
 'countriesAndTerritories_Saint_Lucia',
 'countriesAndTerritories_Saint_Vincent_and_the_Grenadines',
 'countriesAndTerritories_San_Marino',
 'countriesAndTerritories_Saudi_Arabia',
 'countriesAndTerritories_Senegal',
 'countriesAndTerritories_Serbia',
 'countriesAndTerritories_Seychelles',
 'countriesAndTerritories_Singapore',
 'countriesAndTerritories_Sint_Maarten',
 'countriesAndTerritories_Slovakia',
 'countriesAndTerritories_Slovenia',
 'countriesAndTerritories_Somalia',
 'countriesAndTerritories_South_Africa',
 'countriesAndTerritories_South_Korea',
 'countriesAndTerritories_South_Sudan',
 'countriesAndTerritories_Spain',
 'countriesAndTerritories_Sri_Lanka',
 'countriesAndTerritories_Sudan',
 'countriesAndTerritories_Suriname',
 'countriesAndTerritories_Sweden',
 'countriesAndTerritories_Switzerland',
 'countriesAndTerritories_Syria',
 'countriesAndTerritories_Taiwan',
 'countriesAndTerritories_Thailand',
 'countriesAndTerritories_Timor_Leste',
 'countriesAndTerritories_Togo',
 'countriesAndTerritories_Trinidad_and_Tobago',
 'countriesAndTerritories_Tunisia',
 'countriesAndTerritories_Turkey',
 'countriesAndTerritories_Turks_and_Caicos_islands',
 'countriesAndTerritories_Uganda',
 'countriesAndTerritories_Ukraine',
 'countriesAndTerritories_United_Arab_Emirates',
 'countriesAndTerritories_United_Kingdom',
 'countriesAndTerritories_United_Republic_of_Tanzania',
 'countriesAndTerritories_United_States_Virgin_Islands',
 'countriesAndTerritories_United_States_of_America',
 'countriesAndTerritories_Uruguay',
 'countriesAndTerritories_Uzbekistan',
 'countriesAndTerritories_Venezuela',
 'countriesAndTerritories_Vietnam',
 'countriesAndTerritories_Zambia',
 'countriesAndTerritories_Zimbabwe']